language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly
  - hhvm

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm


before_script:
  - composer self-update
  - composer update --prefer-source --no-interaction ${COMPOSER_FLAGS}

script: vendor/bin/phpunit
